### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by vlsi** [mojohaus/javacc-maven-plugin#1]
Is the project still maintained?

I'm interested in adding "do not overwrite file if not modified" feature.
That would enable incremental compilation.

Could it be merged to the javacc-maven-plugin?

**Comment by khmarbaise** [comment]
The needs some work to do to get it up-to-date...but if you like create a pull request....

**Comment by vlsi** [comment]
Closing as updates to  javacc-maven-plugin are not required at this point.

The original issue was caused by fmpp-maven-plugin which we use to generate input for JavaCC.
fmpp-maven-plugin updated the file every time and it caused JavaCC processing.

There's open https://github.com/freemarker/fmpp/issues/11, however org.apache.drill.tools:drill-fmpp-maven-plugin has workaround for that.
