### ISSUE TITLE
release newest version to mavencentral

### ISSUE THREAD

**Issue by stbischof** [mojohaus/javacc-maven-plugin#21]
@olamy olamy 

could you release the newest version to mavencentral?

**Comment by slawekjaranowski** [comment]
It will be appreciated to fix: #22 before release

**Comment by olamy** [comment]
Appreciated but not mandatory ;)

**Comment by fax4ever** [comment]
Hi everybody, I think that this plugin is very nice.
I tested some use cases of the project for which I work and it seems it works pretty well.
It would be great if the newest version was published to maven central.

**Comment by olamy** [comment]
release done

**Comment by fax4ever** [comment]
thank you, really appreciate it
