### ISSUE TITLE
Per-file options broken by javacc-maven-plugin 3.0.0

### ISSUE THREAD

**Issue by cesarb** [mojohaus/javacc-maven-plugin#25]
Since https://github.com/mojohaus/javacc-maven-plugin/pull/16 `javacc-maven-plugin` explicitly sets all options, which breaks per-file overrides, leading to error messages like the following (and the options in the file not being applied):

```
Warning: Line 4, Column 5: Command line setting of "ignore_case" modifies option value in file.
```

If the options are the same in all files, a workaround would be to also set them in the `pom.xml`, but that's not helpful when some files have different options (for instance, some have `ignore_case = true` while others have `ignore_case = false`).

The root cause seems to be that https://github.com/mojohaus/javacc-maven-plugin/pull/16 changed `AbstractJavaCCMojo` to use `boolean` (unboxed) instead of `Boolean` (boxed), which meant that the code in the `JavaCC` class which sets the command line options only when the corresponding value is not `null` does not work correctly anymore, since a `null` value is no longer possible.

**Comment by olamy** [comment]
good analysis 
would you be happy to propose a pull request to fix it?
then I can expedite a quick bug fix release.
cheers

**Comment by cesarb** [comment]
> good analysis would you be happy to propose a pull request to fix it? then I can expedite a quick bug fix release. cheers

Sure, just did it in #27.
