### ISSUE TITLE
maven plugin validation issue

### ISSUE THREAD

**Issue by thebluemountain** [mojohaus/javacc-maven-plugin#54]
I am using the plugin org.codehaus.mojo:javacc-maven-plugin:3.0.1 in a project.
I have updated the maven tool to version 3.9.2

mvn -v
Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: ...
Java version: 11.0.18, vendor: Oracle Corporation, runtime: /opt/java/jdk-11.0.18
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.0-23-amd64", arch: "amd64", family: "unix"

building the project outputs the following warning at the end:

[WARNING] 
[WARNING] Plugin validation issues were detected in 2 plugin(s)
[WARNING] 
[WARNING]  * **org.codehaus.mojo:javacc-maven-plugin:3.0.1**
[WARNING]  * org.apache.maven.plugins:maven-war-plugin:3.3.2
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 

My understanding of this warning is to let us know that these plugin(s) will fail to run with maven 4.x.
(see https://maven.apache.org/docs/3.9.2/release-notes.html)

Q: Is there something that can be done to have the java-cc plugin compatible with maven 4 ?

**Comment by slawekjaranowski** [comment]
PR #48 should resolve it
